# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Guia Laravel
site_url: https://mjtf3.github.io/guia-laravel/
nav:
  - Inicio: "index.md"
  - Instalación: "installation.md"
  - Logging: "logging.md"
  - Testing: "testing.md"
  - Migraciones: "migrations.md"
  - Seeders: "seeders.md"
theme:
  name: material
  features:
    - content.code.copy
